---
title: "writing_functions"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() +
  theme(legend.position = "bottom"))


options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Do Something simple

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

I want a function to compute z-scores

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if (length(x) < 3) {
    stop("Input must be numeric")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
}

z_scores(x_vec)
```

Try my function on some other things: should give errors

```{r, error=TRUE}
z_scores(3)
z_scores("my name is jeff")
z_scores(mtcars)
z_scores(c(TRUE, TRUE, FALSE, FALSE))
```

## Multiple outputs

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if (length(x) < 3) {
    stop("Input must be numeric")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}
```

Check that the function works

```{r}
mean_and_sd(x_vec)
```


## Multiple inputs

```{r}
sim_data =
  tibble(
    x = rnorm(100, mean = 4, sd = 3)
  )

sim_data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )

```

```{r}
sim_mean_sd = function(sample_size, mu = 6, sigma = 4) {
  
  sim_data =
  tibble(
    x = rnorm(n = sample_size, mean = mu, sd = sigma)
  )

sim_data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )
}
```

```{r}
sim_mean_sd(100,6,3)
sim_mean_sd(sample_size = 10, mu = 6, sigma = 3)
```

